// <auto-generated> by tools/gen_mannequin_data.py - do not edit by hand. </auto-generated>
#nullable enable
using System.Numerics;

namespace LowPolyCharGen;

/// <summary>
/// Reference (A-pose) world transforms of the main bones of the UE5 mannequin (SKM_Manny),
/// converted to the generator's right-handed space: +X = character left, -Y = front, +Z = up, centimetres.
/// </summary>
internal static class MannequinData
{
    internal readonly record struct Entry(string Name, string? Parent, Vector3 Position, Quaternion Rotation);

    internal static readonly Entry[] Bones =
    [
        new("root", null, new Vector3(0.0000f, -0.0000f, 0.0000f), new Quaternion(-0.000000f, 0.000000f, -0.000000f, 1.000000f)),
        new("pelvis", "root", new Vector3(-0.0000f, -2.2809f, 95.8968f), new Quaternion(-0.022415f, -0.706751f, 0.022415f, 0.706751f)),
        new("spine_01", "pelvis", new Vector3(0.0000f, -2.0479f, 99.5664f), new Quaternion(0.066693f, -0.703955f, -0.066693f, 0.703955f)),
        new("spine_02", "spine_01", new Vector3(-0.0000f, -3.3239f, 106.2406f), new Quaternion(0.045383f, -0.705649f, -0.045383f, 0.705649f)),
        new("spine_03", "spine_02", new Vector3(-0.0000f, -4.2512f, 113.4192f), new Quaternion(-0.022126f, -0.706761f, 0.022126f, 0.706761f)),
        new("spine_04", "spine_03", new Vector3(-0.0000f, -3.7180f, 121.9264f), new Quaternion(-0.058264f, -0.704702f, 0.058270f, 0.704702f)),
        new("spine_05", "spine_04", new Vector3(0.0000f, -0.5251f, 141.1022f), new Quaternion(-0.062456f, -0.704343f, 0.062456f, 0.704343f)),
        new("neck_01", "spine_05", new Vector3(-0.0000f, 1.5667f, 152.8045f), new Quaternion(0.084911f, -0.701990f, -0.084911f, 0.701990f)),
        new("neck_02", "neck_01", new Vector3(-0.0000f, 0.3483f, 157.7674f), new Quaternion(0.073177f, -0.703310f, -0.073178f, 0.703310f)),
        new("head", "neck_02", new Vector3(-0.0000f, -0.6631f, 162.5751f), new Quaternion(-0.000000f, -0.707107f, 0.000000f, 0.707107f)),
        new("clavicle_l", "spine_05", new Vector3(1.4279f, 1.7398f, 146.3011f), new Quaternion(0.000039f, 0.076541f, 0.023020f, 0.996801f)),
        new("upperarm_l", "clavicle_l", new Vector3(19.0099f, 2.5572f, 143.5835f), new Quaternion(-0.030411f, 0.460409f, 0.002586f, 0.887182f)),
        new("lowerarm_l", "upperarm_l", new Vector3(35.0070f, 1.9070f, 120.8920f), new Quaternion(-0.182276f, 0.423883f, -0.293555f, 0.837212f)),
        new("hand_l", "lowerarm_l", new Vector3(47.7686f, -15.6989f, 104.4665f), new Quaternion(-0.608875f, 0.520600f, 0.009649f, 0.598460f)),
        new("clavicle_r", "spine_05", new Vector3(-1.4279f, 1.7398f, 146.3010f), new Quaternion(-0.996801f, 0.023020f, -0.076541f, 0.000039f)),
        new("upperarm_r", "clavicle_r", new Vector3(-19.0099f, 2.5573f, 143.5830f), new Quaternion(0.887182f, -0.002586f, 0.460409f, 0.030411f)),
        new("lowerarm_r", "upperarm_r", new Vector3(-35.0067f, 1.9071f, 120.8918f), new Quaternion(0.837212f, 0.293555f, 0.423883f, 0.182276f)),
        new("hand_r", "lowerarm_r", new Vector3(-47.7683f, -15.6988f, 104.4664f), new Quaternion(0.598460f, -0.009649f, 0.520600f, 0.608875f)),
        new("thigh_l", "pelvis", new Vector3(9.9692f, -2.5406f, 93.5428f), new Quaternion(0.049970f, -0.724140f, 0.053695f, 0.685741f)),
        new("calf_l", "thigh_l", new Vector3(12.3323f, -2.5957f, 50.2660f), new Quaternion(0.081540f, -0.721268f, 0.023704f, 0.687432f)),
        new("foot_l", "calf_l", new Vector3(14.0877f, 0.9943f, 8.2376f), new Quaternion(0.063632f, -0.704247f, 0.041376f, 0.705887f)),
        new("ball_l", "foot_l", new Vector3(15.7779f, -13.9288f, 0.7508f), new Quaternion(0.542972f, -0.452983f, -0.469880f, 0.528394f)),
        new("thigh_r", "pelvis", new Vector3(-9.9691f, -2.5500f, 93.5434f), new Quaternion(-0.685741f, 0.053695f, 0.724140f, 0.049970f)),
        new("calf_r", "thigh_r", new Vector3(-12.3322f, -2.6051f, 50.2666f), new Quaternion(-0.687432f, 0.023704f, 0.721268f, 0.081540f)),
        new("foot_r", "calf_r", new Vector3(-14.0876f, 0.9848f, 8.2382f), new Quaternion(-0.705887f, 0.041376f, 0.704247f, 0.063632f)),
        new("ball_r", "foot_r", new Vector3(-15.7777f, -13.9382f, 0.7514f), new Quaternion(-0.528394f, -0.469880f, 0.452983f, 0.542972f)),
    ];
}
