// <auto-generated> by tools/gen_toon_data.py - do not edit by hand. </auto-generated>
#nullable enable
using System.Numerics;

namespace LowPolyCharGen;

/// <summary>
/// Reference-pose world transforms of the Toon Soldiers pack skeleton (Characters_Skeleton, a 3ds Max
/// Biped), converted to the generator's right-handed space: +X = character left, -Y = front, +Z = up,
/// centimetres. Scale is the bone's world scale (Bip001 carries 1.8 and every child inherits it).
/// </summary>
internal static class ToonSoldierData
{
    internal readonly record struct Entry(string Name, string? Parent, Vector3 Position, Quaternion Rotation, float Scale);

    internal static readonly Entry[] Bones =
    [
        new("Bip001", null, new Vector3(0.0000f, 2.5252f, 86.7054f), new Quaternion(0.000000f, 0.000000f, -0.707106f, 0.707107f), 1.8000f),
        new("Bip001-Pelvis", "Bip001", new Vector3(0.0000f, 2.5252f, 86.7054f), new Quaternion(-0.707107f, -0.000000f, -0.707107f, 0.000001f), 1.8000f),
        new("Bip001-Spine", "Bip001-Pelvis", new Vector3(-0.0000f, 2.5585f, 98.1272f), new Quaternion(-0.707039f, 0.009787f, -0.707040f, 0.009786f), 1.8000f),
        new("Bip001-Neck", "Bip001-Spine", new Vector3(0.0000f, 0.9464f, 142.9649f), new Quaternion(-0.700502f, 0.096420f, -0.700502f, 0.096419f), 1.8000f),
        new("Bip001-Head", "Bip001-Neck", new Vector3(-0.0001f, -1.4484f, 151.4998f), new Quaternion(0.707107f, -0.000001f, 0.707107f, 0.000000f), 1.8000f),
        new("Bip001-L-Clavicle", "Bip001-Spine", new Vector3(9.0250f, 1.3969f, 138.5099f), new Quaternion(0.010265f, 0.056163f, 0.055675f, 0.996815f), 1.8000f),
        new("Bip001-L-UpperArm", "Bip001-L-Clavicle", new Vector3(26.4979f, 3.3813f, 136.5489f), new Quaternion(0.050443f, 0.057578f, 0.012510f, 0.996987f), 1.8000f),
        new("Bip001-L-Forearm", "Bip001-L-UpperArm", new Vector3(54.9634f, 4.2628f, 133.2942f), new Quaternion(0.046806f, 0.060572f, -0.048840f, 0.995869f), 1.8000f),
        new("Bip001-L-Hand", "Bip001-L-Forearm", new Vector3(78.8837f, 2.0447f, 130.2623f), new Quaternion(-0.670795f, 0.077369f, 0.008265f, 0.737550f), 1.8000f),
        new("WeaponContainer_L", "Bip001-L-Hand", new Vector3(90.0000f, -9.5851f, 125.3900f), new Quaternion(0.000002f, -0.000000f, 0.000000f, 1.000000f), 1.8000f),
        new("Bip001-R-Clavicle", "Bip001-Spine", new Vector3(-9.0252f, 1.3969f, 138.5099f), new Quaternion(0.055674f, 0.996815f, 0.010266f, 0.056164f), 1.8000f),
        new("Bip001-R-UpperArm", "Bip001-R-Clavicle", new Vector3(-26.4981f, 3.3812f, 136.5489f), new Quaternion(0.012509f, 0.996987f, 0.050443f, 0.057579f), 1.8000f),
        new("Bip001-R-Forearm", "Bip001-R-UpperArm", new Vector3(-54.9636f, 4.2627f, 133.2940f), new Quaternion(-0.048841f, 0.995869f, 0.046806f, 0.060573f), 1.8000f),
        new("Bip001-R-Hand", "Bip001-R-Forearm", new Vector3(-78.8839f, 2.0445f, 130.2620f), new Quaternion(0.008265f, 0.737549f, -0.670795f, 0.077371f), 1.8000f),
        new("WeaponContainer", "Bip001-R-Hand", new Vector3(-90.0263f, -9.5851f, 125.3900f), new Quaternion(0.000000f, 1.000000f, 0.000002f, 0.000000f), 1.8000f),
        new("Backpack_container", "Bip001-Spine", new Vector3(-0.0000f, 20.8641f, 131.1677f), new Quaternion(-0.707257f, 0.000001f, -0.000002f, 0.706957f), 1.8000f),
        new("Bip001-L-Thigh", "Bip001-Pelvis", new Vector3(13.4395f, 2.5252f, 86.7054f), new Quaternion(0.715360f, -0.013364f, -0.698516f, 0.012526f), 1.8000f),
        new("Bip001-L-Calf", "Bip001-L-Thigh", new Vector3(14.4671f, 0.9437f, 43.5589f), new Quaternion(-0.715088f, -0.023844f, 0.698222f, 0.023806f), 1.8000f),
        new("Bip001-L-Foot", "Bip001-L-Calf", new Vector3(15.1900f, 2.9863f, 13.3063f), new Quaternion(-0.707107f, -0.000001f, 0.707106f, 0.000000f), 1.8000f),
        new("Bip001-L-Toe0", "Bip001-L-Foot", new Vector3(15.1901f, -16.3479f, 0.4638f), new Quaternion(0.500001f, -0.500000f, -0.500000f, 0.500000f), 1.8000f),
        new("Bip001-R-Thigh", "Bip001-Pelvis", new Vector3(-13.4395f, 2.5251f, 86.7054f), new Quaternion(0.698517f, -0.012525f, -0.715359f, 0.013365f), 1.8000f),
        new("Bip001-R-Calf", "Bip001-R-Thigh", new Vector3(-14.4670f, 0.9437f, 43.5588f), new Quaternion(-0.698223f, -0.023807f, 0.715087f, 0.023843f), 1.8000f),
        new("Bip001-R-Foot", "Bip001-R-Calf", new Vector3(-15.1898f, 2.9862f, 13.3063f), new Quaternion(-0.707107f, -0.000001f, 0.707106f, 0.000000f), 1.8000f),
        new("Bip001-R-Toe0", "Bip001-R-Foot", new Vector3(-15.1898f, -16.3479f, 0.4638f), new Quaternion(0.500001f, -0.500000f, -0.500000f, 0.500000f), 1.8000f),
    ];
}
