"""Generates ToonSoldierData.cs from a reference-pose dump of the Toon Soldiers pack skeleton.

The dump (toon_soldiers_skeleton.json) is taken in the Unreal Editor from one of the pack's
skeletal meshes (SK_Armies_Soldier_A) with SkeletonModifier.get_bone_transform(name, global=True),
so it is the reference pose the pack's meshes are bound in, including the 1.8 scale every bone
inherits from Bip001.

Unreal space is left-handed (+X = character left, +Y = front, +Z = up); the generator uses the
right-handed space of the FBX file (+X = left, -Y = front, +Z = up), so Y is negated and
quaternions are mirrored: (x, y, z, w) -> (-x, y, -z, w).

usage: python gen_toon_data.py toon_soldiers_skeleton.json ../src/LowPolyCharGen.Core/ToonSoldierData.cs
"""
import json
import sys


def main():
    src, dst = sys.argv[1], sys.argv[2]
    bones = json.load(open(src))["bones"]
    lines = []
    for b in bones:
        g = b["global"]
        x, y, z = g["t"]
        qx, qy, qz, qw = g["q"]
        y = -y
        qx, qz = -qx, -qz
        if qw < 0:
            qx, qy, qz, qw = -qx, -qy, -qz, -qw
        s = g["s"][0]
        parent = b["parent"]
        p = "null" if parent in ("None", "", None) else f'"{parent}"'
        lines.append(
            f'        new("{b["name"]}", {p}, new Vector3({x:.4f}f, {y:.4f}f, {z:.4f}f), '
            f"new Quaternion({qx:.6f}f, {qy:.6f}f, {qz:.6f}f, {qw:.6f}f), {s:.4f}f),")
    out = f"""// <auto-generated> by tools/gen_toon_data.py - do not edit by hand. </auto-generated>
#nullable enable
using System.Numerics;

namespace LowPolyCharGen;

/// <summary>
/// Reference-pose world transforms of the Toon Soldiers pack skeleton (Characters_Skeleton, a 3ds Max
/// Biped), converted to the generator's right-handed space: +X = character left, -Y = front, +Z = up,
/// centimetres. Scale is the bone's world scale (Bip001 carries 1.8 and every child inherits it).
/// </summary>
internal static class ToonSoldierData
{{
    internal readonly record struct Entry(string Name, string? Parent, Vector3 Position, Quaternion Rotation, float Scale);

    internal static readonly Entry[] Bones =
    [
{chr(10).join(lines)}
    ];
}}
"""
    open(dst, "w", newline="\n").write(out)


if __name__ == "__main__":
    main()
