"""Generates MannequinData.cs from a reference-pose dump of the UE5 mannequin.

The dump (manny_bones.json) is produced inside the Unreal Editor with
AnimPoseExtensions.get_reference_pose / get_bone_pose (world space).

Unreal space is left-handed (+X = character left, +Y = front, +Z = up).
The generator works in the right-handed space the FBX file uses
(+X = character left, -Y = front, +Z = up), so Y is negated here and
quaternions are mirrored to match: (x, y, z, w) -> (-x, y, -z, w).

usage: python gen_mannequin_data.py manny_bones.json ../src/LowPolyCharGen.Core/MannequinData.cs
"""
import json
import sys

BONES = [
    ("root", None),
    ("pelvis", "root"),
    ("spine_01", "pelvis"), ("spine_02", "spine_01"), ("spine_03", "spine_02"),
    ("spine_04", "spine_03"), ("spine_05", "spine_04"),
    ("neck_01", "spine_05"), ("neck_02", "neck_01"), ("head", "neck_02"),
    ("clavicle_l", "spine_05"), ("upperarm_l", "clavicle_l"), ("lowerarm_l", "upperarm_l"), ("hand_l", "lowerarm_l"),
    ("clavicle_r", "spine_05"), ("upperarm_r", "clavicle_r"), ("lowerarm_r", "upperarm_r"), ("hand_r", "lowerarm_r"),
    ("thigh_l", "pelvis"), ("calf_l", "thigh_l"), ("foot_l", "calf_l"), ("ball_l", "foot_l"),
    ("thigh_r", "pelvis"), ("calf_r", "thigh_r"), ("foot_r", "calf_r"), ("ball_r", "foot_r"),
]


def main():
    src, dst = sys.argv[1], sys.argv[2]
    data = {b["name"]: b for b in json.load(open(src))}
    lines = []
    for name, parent in BONES:
        w = data[name]["world"]
        x, y, z = w["t"]
        qx, qy, qz, qw = w["q"]
        y = -y
        qx, qz = -qx, -qz
        if qw < 0:
            qx, qy, qz, qw = -qx, -qy, -qz, -qw
        p = "null" if parent is None else f'"{parent}"'
        lines.append(
            f'        new("{name}", {p}, new Vector3({x:.4f}f, {y:.4f}f, {z:.4f}f), '
            f"new Quaternion({qx:.6f}f, {qy:.6f}f, {qz:.6f}f, {qw:.6f}f)),")
    out = f"""// <auto-generated> by tools/gen_mannequin_data.py - do not edit by hand. </auto-generated>
#nullable enable
using System.Numerics;

namespace LowPolyCharGen;

/// <summary>
/// Reference (A-pose) world transforms of the main bones of the UE5 mannequin (SKM_Manny),
/// converted to the generator's right-handed space: +X = character left, -Y = front, +Z = up, centimetres.
/// </summary>
internal static class MannequinData
{{
    internal readonly record struct Entry(string Name, string? Parent, Vector3 Position, Quaternion Rotation);

    internal static readonly Entry[] Bones =
    [
{chr(10).join(lines)}
    ];
}}
"""
    open(dst, "w", encoding="utf-8", newline="\n").write(out)
    print("wrote", dst, len(BONES), "bones")


if __name__ == "__main__":
    main()
